[web]
worker-node1 ansible_host=18.234.39.161 ansible_user=ubuntu
worker-node2 ansible_host=52.90.216.108 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/keys/ansible-project
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false