---
- name: Apply common configuration
  hosts: all
  become: true
  roles:
    - common
  tags: common


- name: Install docker
  hosts: web
  become: true
  roles:
    - docker
  tags: docker

- name: nginx config
  hosts: web
  become: true
  roles:
    - nginx
  tags: nginx