- name: Restart Docker
  service:
    name: docker
    state: restarted

ubuntu@ip-172-31-34-79:~/ansible-project/roles/docker/handlers$ cd ..
ubuntu@ip-172-31-34-79:~/ansible-project/roles/docker$ cd tasks
ubuntu@ip-172-31-34-79:~/ansible-project/roles/docker/tasks$ ls
main.yml
ubuntu@ip-172-31-34-79:~/ansible-project/roles/docker/tasks$ cat main.yml
#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker



    - name: install docker dependencices
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      tags: docker

    - name: install docker
      shell: |
        curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker
      tags: docker

    - name: enable the docker
      systemd:
        name: docker
        enabled: yes
        state: started
      tags: docker

    - name: adding the user to docker group
      user:
        name: deploy
        groups: docker
        append: true
      tags: docker
    - name: install docker compose plugin
      apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes
      ignore_errors: yes
      tags: docker

    - name: login to docker hub
      community.docker.docker_login:
        username: "{{ vault_docker_username }}"
        password: "{{ vault_docker_password }}"
      when: vault_docker_username is defined
      tags: docker

    - name: pull image
      community.docker.docker_image:
        name: "{{ docker_app_image }}"
        tag: "{{ docker_app_tag }}"
        source: pull
    - name: run the container
      community.docker.docker_container:
        name: "{{ docker_app_name }}"
        image: "{{ docker_app_image }}:{{ docker_app_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ docker_app_port }}:{{ docker_container_port }}"
      tags: docker

    - name: Wait for container to be healthy
      uri:
        url: "http://localhost:{{ docker_app_port }}"
        status_code: 200
      retries: 5
      delay: 3
      register: health_check
      until: health_check.status == 200
      tags: docker