name: reusable docker

on:
    workflow_call:
        secrets: 
            DOCKER_PASS:
                required: true
        inputs:
            image_name:
                type: string
                required: true
            tag: 
                type: string
                required: true
            docker_user:
                type: string
                required: true
        outputs:
            image_url:
                value: ${{jobs.docker-reusable.outputs.imageurl}}

jobs:
    docker-reusable:
        runs-on: ubuntu-latest
        outputs:
            imageurl: ${{ steps.ImageUrlId.outputs.ImageUrl }}
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: docker login 
              uses: docker/login-action@v4
              with: 
                username: ${{ inputs.docker_user }}
                password: ${{ secrets.DOCKER_PASS }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with: 
                context: 
                file: ./Dockerfile
                push: true
                tags: |
                   ${{inputs.tag}}:latest
                   ${{inputs.tag}}:${{github.sha}}

            - name: set image url
              id: ImageUrlId
              run: |
                 echo "ImageUrl=${{inputs.docker_user}}:${{github.sha}}" >> GITHUB_OUTPUT