apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
    namespace: capstone
    labels:
        app: wordpress
spec:
    replicas: 2
    selector:
        matchLabels:
            app: wordpress
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
             - name: wordpress
               image: wordpress:latest
               envFrom:
                 - configMapRef:
                     name: config
               env:
               - name: WORDPRESS_DB_USER
                 valueFrom:
                   secretKeyRef:
                       name: secrets
                       key: MYSQL_USER
               - name: WORDPRESS_DB_PASSWORD
                 valueFrom:
                   secretKeyRef:
                       name: secrets
                       key: MYSQL_PASSWORD
               resources:
                   requests:
                       cpu: "100m"
                       memory: "256Mi"
                   limits:
                       cpu: "250m"
                       memory: "512Mi"
               livenessProbe:
                   httpGet:
                       path: /wp-login.php
                       port: 80
                   initialDelaySeconds: 60
                   periodSeconds: 10
                   failureThreshold: 5
               readinessProbe:
                   httpGet:
                       path: /wp-login.php
                       port: 80
                   initialDelaySeconds: 30
                   periodSeconds: 5
                   failureThreshold: 5

